/* Creator research remains device-local, separate from app records and timed tests. */
(()=>{
 const KEY='memoive-evidence-v1',E=EvidenceTools,$=id=>document.getElementById(id),esc=escapeHtml;
 let data={format:KEY,cases:[],observations:[],decisions:[]},expected=null,blocked=false;
 const host=document.createElement('section');host.id='evidence-lab';host.setAttribute('aria-labelledby','evidence-title');
 document.querySelector('aside.notice').after(host);
 host.innerHTML=`<p class="eyebrow">DECISIONS WITH EVIDENCE</p><h2 id="evidence-title">기획·검증 노트</h2><p>가설과 실제 관찰을 구분하고, 무엇을 왜 바꿨는지 연결해요. 외부 사용자에게 확인하지 않았다면 미검증으로 남깁니다.</p><p class="hint">이 브라우저 전용입니다. 이름·연락처·민감한 발언 원문 대신 익명 코드와 필요한 요지만 적어주세요. 메모는 AI로 보내지 않습니다.</p><div id="evidence-overview"></div>
 <details open><summary>1. 검증할 문제 정하기</summary><form id="hypothesis-form"><label>문제 이름<input name="title" required maxlength="120" placeholder="예: 저장한 기록을 글쓰기 재료로 다시 찾기"></label><label>누구의 어떤 상황인가요?<input name="target" required maxlength="4000" placeholder="직무명이 아니라 실제 작업 상황을 적어주세요."></label><label>확인할 가설<textarea name="hypothesis" required maxlength="4000" rows="2"></textarea></label><label>주로 볼 지표<input name="metric" required maxlength="4000" placeholder="예: 도움 없이 목표 기록을 찾은 횟수 / 시도 횟수"></label><label>어떤 결과면 유지·수정할까요?<textarea name="criterion" required maxlength="4000" rows="2" placeholder="결과를 보기 전에 판단 기준과 관찰 기간을 정해 주세요."></textarea></label><label>함께 지킬 조건<input name="guardrail" required maxlength="4000" placeholder="예: 속도가 빨라도 잘못된 기록을 찾으면 성공으로 보지 않기"></label><button>새 가설 저장</button></form></details>
 <details><summary>2. 실제 관찰과 반례 남기기</summary><form id="observation-form"><label>문제 가설<select name="caseId" required data-case-select></select></label><label>근거를 얻은 방식<select name="kind"><option value="self">제작자 직접 사용</option><option value="interview">대상 사용자 인터뷰</option><option value="observation">대상 사용자 행동 관찰</option></select></label><label>익명 참여자 코드<input name="participant" required maxlength="60" placeholder="예: 본인 / P01 · 같은 사람은 같은 코드"></label><label>실제로 확인한 날짜<input name="date" type="date" required></label><label>실제로 본 행동·들은 내용<textarea name="behavior" required maxlength="4000" rows="3"></textarea></label><label>그 내용에 대한 나의 해석<textarea name="interpretation" required maxlength="4000" rows="2" placeholder="관찰만으로 알 수 없는 부분도 적어주세요."></textarea></label><label>현재 어떻게 해결하고 있나요?<input name="alternative" required maxlength="4000" placeholder="기존 도구·행동 또는 확인하지 못함"></label><label>가설과 어떤 관계인가요?<select name="direction"><option value="unclear">아직 판단하기 어려움</option><option value="support">가설을 뒷받침하는 관찰</option><option value="counter">가설과 다른 관찰·반례</option></select></label><button>관찰 근거 저장</button></form></details>
 <details><summary>3. 근거를 보고 개선 결정하기</summary><form id="decision-form"><label>문제 가설<select name="caseId" required data-case-select></select></label><fieldset id="decision-evidence"><legend>판단에 사용한 관찰</legend><div id="evidence-options"></div></fieldset><label>실제로 바꿀 한 가지<textarea name="change" required maxlength="4000" rows="2"></textarea></label><label>고려했지만 제외한 대안<textarea name="alternative" required maxlength="4000" rows="2"></textarea></label><label>왜 이 안을 먼저 선택했나요?<textarea name="rationale" required maxlength="4000" rows="2"></textarea></label><label>적용할 버전<input name="version" required maxlength="120" placeholder="예: 검색 개선 v1"></label><button>개선 결정 저장</button></form></details>
 <details><summary>4. 근거와 변경 전후 결과 보기</summary><div id="evidence-report"></div><p class="hint">아래 시간 측정에서 가설·개선 결정을 선택하면 연결됩니다. 시험 횟수를 사용자 수로 세지 않아요.</p><button id="evidence-preview" type="button" class="secondary">포트폴리오 기록 미리 보기</button><textarea id="evidence-preview-text" rows="10" readonly hidden aria-label="포트폴리오 기록 미리 보기"></textarea><button id="evidence-markdown" type="button" class="secondary" hidden>검토한 기록 내려받기</button></details>
 <details><summary>기획 근거 백업·복원</summary><p class="hint">가설·관찰·개선 결정만 포함해요. 시간 측정은 페이지 아래의 테스트 백업도 함께 보관하세요. 내보낸 메모에 개인 정보가 없는지 확인해 주세요.</p><button id="evidence-backup" type="button" class="secondary">기획 근거 백업 저장</button><label>기획 근거 백업 합치기<input id="evidence-import" type="file" accept="application/json,.json"></label></details><p id="evidence-status" role="status" aria-live="polite"></p>`;
 const feedback=message=>$('evidence-status').textContent=message;
 try{expected=localStorage.getItem(KEY);if(expected)data=E.validate(JSON.parse(expected));}catch{blocked=true;feedback('기획 근거를 읽지 못했어요. 원본을 덮어쓰지 않습니다. 백업을 확인해 주세요.');}
 function commit(next){if(blocked)throw Error('읽지 못한 원본이 있어 저장하지 않았어요.');if(localStorage.getItem(KEY)!==expected)throw Error('다른 탭에서 근거가 바뀌었어요. 입력을 복사해 둔 뒤 새로고침해 주세요.');const valid=E.validate(next),packed=JSON.stringify(valid);localStorage.setItem(KEY,packed);expected=packed;data=valid;render();}
 function studyRows(){try{return readAttempts();}catch{return [];}}
 function fillSelect(select,rows,label){const selected=(select.id==='caseId'||select.id==='decisionId')&&draft?draft[select.id]||'':select.value;select.innerHTML='<option value="">선택하지 않음</option>'+rows.map(r=>`<option value="${esc(r.id)}">${esc(label(r))}</option>`).join('');select.value=selected;}
 function options(){const selected=$('decision-form').elements.caseId.value;$('evidence-options').innerHTML=data.observations.filter(o=>o.caseId===selected).map(o=>`<label class="evidence-choice"><input type="checkbox" name="evidenceIds" value="${esc(o.id)}"><span>${esc(o.behavior)} <small>· ${esc(o.direction==='counter'?'반례':o.kind==='self'?'본인':'외부 관찰')}</small></span></label>`).join('')||'<p class="hint">이 가설에 연결된 관찰을 먼저 남겨주세요.</p>';}
 function decisions(){fillSelect($('decisionId'),data.decisions.filter(d=>d.caseId===$('caseId').value),d=>`${d.version} · ${d.change}`);}
 function render(){
   const external=data.observations.filter(o=>o.kind!=='self');$('evidence-overview').innerHTML=`<div class="result"><strong>${data.cases.length}개 가설 · ${data.observations.length}개 관찰 · ${data.decisions.length}개 결정</strong>${external.length?'외부 관찰 기록이 있습니다. 표본 대표성·수요 확정은 별도 검증이 필요해요.':'대상 사용자 수요: 아직 외부 근거가 없어요.'}</div>`;
   document.querySelectorAll('[data-case-select]').forEach(s=>fillSelect(s,data.cases,c=>c.title));fillSelect($('caseId'),data.cases,c=>c.title);decisions();options();
   const rows=studyRows();$('evidence-report').innerHTML=data.cases.map(c=>{const obs=data.observations.filter(o=>o.caseId===c.id),runs=rows.filter(r=>r.caseId===c.id),ds=data.decisions.filter(d=>d.caseId===c.id),pairs=runs.filter(r=>r.previousId).map(r=>({r,c:E.compare(r,rows)}));return `<article class="result"><strong>${esc(c.title)}</strong><p>관찰 ${obs.length}건 · 반례 ${obs.filter(o=>o.direction==='counter').length}건 · 결정 ${ds.length}건 · 제작자 시험 ${runs.length}회</p><p>${pairs.length?pairs.map(p=>p.c.comparable?`조건 일치 비교 · ${p.c.delta===null?'두 시험 모두 도움 없이 완료한 경우가 아니므로 시간 차이 미표시':`이후−이전 ${p.c.delta}초`}`:'조건 불일치 · '+p.c.reasons.join(' ')).map(esc).join('<br>'):'변경 전후 비교 근거는 아직 없어요.'}</p><p>막힘 위치(시험 응답): ${Object.entries(E.stages).map(([key,label])=>{const n=runs.filter(r=>(r.frictionStage||'unknown')===key).length;return n?esc(label)+' '+n+'회':'';}).filter(Boolean).join(' · ')||'응답 없음'}</p><p>${runs.some(r=>Date.parse(r.startedAt)<Date.parse(c.at))?'가설 작성 전의 시험이 포함되어 있어 사전 설계 검증으로 해석하지 않습니다.':'시험 전 가설·판정 기준을 남기고 실패 결과도 보관하세요.'}</p><small>조건 일치도 학습효과를 제거하거나 개선 효과를 입증하지는 않습니다.</small></article>`;}).join('')||'<p>아직 검증할 가설이 없어요. 첫 가설을 적어보세요.</p>';
   $('evidence-preview-text').hidden=true;$('evidence-markdown').hidden=true;
 }
 for(const [formId,key] of [['hypothesis-form','cases'],['observation-form','observations'],['decision-form','decisions']])$(formId).onsubmit=event=>{event.preventDefault();const form=event.target,r=Object.fromEntries(new FormData(form));r.id=crypto.randomUUID();r.at=new Date().toISOString();if(key==='observations'){const date=new Date(r.date+'T12:00:00');if(!Number.isFinite(date.getTime())||date.toDateString()!==new Date().toDateString()&&date>Date.now()){feedback('실제로 관찰한 오늘 또는 이전 날짜를 적어주세요.');return;}r.at=date.toISOString();}if(key==='decisions')r.evidenceIds=new FormData(form).getAll('evidenceIds');try{commit({...data,[key]:[...data[key],r]});form.reset();options();feedback('근거를 이 브라우저에 저장했어요. 실제 검증 결과를 자동으로 만들지는 않습니다.');}catch(e){feedback(e.message||'저장하지 못했어요. 입력은 그대로입니다.');}};
 $('decision-form').elements.caseId.onchange=options;$('caseId').addEventListener('change',decisions);
 $('decisionId').addEventListener('change',()=>{const d=data.decisions.find(d=>d.id===$('decisionId').value);if(d&&!draft){$('version').value=d.version;$('change').value=d.change;}});
 $('evidence-backup').onclick=()=>download(JSON.stringify(data,null,2),`memoive-evidence-${Date.now()}.json`,'application/json');
 $('evidence-import').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('2MB 이하의 백업을 선택해 주세요.');commit(E.merge(data,JSON.parse(await file.text())));feedback('현재 근거를 덮어쓰지 않고 백업을 합쳤어요.');}catch(e){feedback(e.message||'복원하지 못했어요.');}finally{event.target.value='';}};
 $('evidence-preview').onclick=()=>{$('evidence-preview-text').value=E.report(data,studyRows());$('evidence-preview-text').hidden=false;$('evidence-markdown').hidden=false;};
 $('evidence-markdown').onclick=()=>download($('evidence-preview-text').value,`memoive-planning-evidence-${Date.now()}.md`,'text/markdown;charset=utf-8');
 window.addEventListener('memoive-study-saved',render);render();
})();
