/* A device-local workbench. Recommendations never make an external request. */
(()=>{
  let active=null,restoring=false,readBlocked=false,showAll=false;
  try{state.workspaces=ReuseTools.cleanWorkspaces(saved?.workspaces);}catch(e){readBlocked=true;state.workspaces=[];showStorageProblem(e.message);}
  const basePersistent=persistentState;
  persistentState=()=>({...basePersistent(),workspaces:state.workspaces});
  lastCommitted=JSON.stringify(persistentState());
  const baseValidate=DataTools.validateBackup;
  DataTools.validateBackup=input=>{const raw=typeof input==='string'?JSON.parse(input):input;return {...baseValidate(raw),workspaces:ReuseTools.cleanWorkspaces(raw.workspaces)};};
  const originalPersist=persist;
  persist=function(){if(readBlocked){const error=new Error('이어 쓰기 저장본을 읽지 못해 덮어쓰기를 중단했어요.');error.name='StorageSafetyError';throw error;}return originalPersist();};
  const form=$('#creator-form'),host=document.createElement('section');host.className='reuse-panel';host.id='reuse-work';
  host.innerHTML=`<label>이번 작업 이름<input id="reuse-name" maxlength="100" placeholder="예: 첫 사용 경험 개선안"></label><p id="reuse-autosave" class="reuse-status" role="status"></p><div id="reuse-summary"></div><details id="reuse-context"><summary>이전 작업의 목적·관점 가져오기</summary><select id="reuse-previous" aria-label="맥락을 가져올 작업"></select><div class="reuse-actions"><button type="button" id="reuse-copy-context">선택한 목적·관점 가져오기</button></div><small>현재 입력은 확인 후 바꿔요. 이전 작업은 수정하지 않아요. 작업은 이 브라우저에 보관되며 다른 기기와 자동 동기화되지 않아요. 설정의 기록 보관함에서 백업할 수 있어요.</small></details>`;
  form.before(host);
  // Purpose before material selection: choose sources for a task, not a blank prompt.
  const purpose=$('#output-purpose').closest('label');form.prepend(purpose);
  const picker=document.createElement('section');picker.className='reuse-panel';picker.id='reuse-picker';
  picker.innerHTML=`<h2>이번에 쓸 자료 고르기</h2><label>작업에 필요한 내용<input id="reuse-query" type="search" placeholder="예: 첫 사용, 고객 인터뷰, 재방문"></label><small>작업 목적 또는 검색어와 겹치는 단어로 찾아요. 의미·찬반을 자동 판정하지 않습니다.</small><div class="reuse-actions"><button type="button" id="reuse-find">관련 자료 찾기</button><button type="button" id="reuse-browse">내 기록 전체 보기</button></div><p id="reuse-find-status" role="status"></p><div id="reuse-candidates"></div><details><summary>이번에는 쓰지 않을 자료</summary><div id="reuse-excluded"></div></details>`;
  $('#creator-sources').closest('fieldset').before(picker);
  const manual=document.createElement('div');manual.hidden=true;const fieldset=$('#creator-sources').closest('fieldset');fieldset.before(manual);manual.append(fieldset);
  const thoughts=document.createElement('section');thoughts.className='reuse-panel';thoughts.id='reuse-thoughts';$('#output-viewpoint').closest('label').before(thoughts);
  const rationale=document.createElement('section');rationale.className='reuse-panel';rationale.id='reuse-decisions';manual.after(rationale);
  const trace=document.createElement('section');trace.className='reuse-panel';trace.id='reuse-trace';
  trace.innerHTML=`<h2>이 문장은 어디에서 왔나요?</h2><p>아래 연결은 직접 선택한 근거예요. 발췌가 원문에 있어도 주장이 맞다는 뜻은 아닙니다.</p><div id="reuse-trace-list"></div><details id="reuse-trace-form"><summary>결과물 문장에 근거 연결하기</summary><button type="button" id="reuse-selected-sentence">편집기에서 선택한 문장 가져오기</button><label>연결할 결과물 문장<textarea id="reuse-claim" rows="2"></textarea></label><label>문장 성격<select id="reuse-kind"><option value="source">원문 내용에 관한 주장</option><option value="interpretation">해석·적용 제안 (원문의 사실 아님)</option><option value="thought">내가 작성한 의견 (원문의 사실 아님)</option></select></label><label>참고 기록<select id="reuse-trace-source"></select></label><div id="reuse-trace-body" class="reuse-source-body" tabindex="0" aria-label="근거를 고를 저장 본문"></div><small>본문에서 구절을 선택하고 아래 버튼을 누르거나 직접 붙여 넣으세요.</small><button type="button" id="reuse-selected-quote">본문에서 선택한 구절 가져오기</button><label>원문 그대로의 발췌<textarea id="reuse-quote" rows="3"></textarea></label><button type="button" id="reuse-add-trace">이 문장과 근거 연결</button><p id="reuse-trace-status" role="status"></p></details>`;
  $('#output-sources').after(trace);
  const overview=document.createElement('section');overview.className='reuse-panel';overview.id='reuse-home';$('[data-screen="home"] .share-tip').after(overview);
  const studio=document.createElement('section');studio.className='reuse-panel';studio.id='reuse-studio';$('.studio-start').before(studio);
  function current(){return state.workspaces.find(w=>w.id===active);}
  window.memoiveWorkOutputMetadata=()=>({workspaceId:active||'',traces:current()?.traces||[]});
  function readFields(){return {name:$('#reuse-name').value,purpose:$('#output-purpose').value,viewpoint:$('#output-viewpoint').value,type:$('#output-type').value,tone:$('#output-tone').value,title:$('#output-title').value,body:$('#output-body').value,selected:selectedCreatorRecords().map(r=>r.id),shareFormat:currentShareFormat(),draftOrigin:analysisDraftOrigin,used:$('#output-used').checked,useNote:$('#output-use-note').value};}
  function saveWork(){if(restoring||!active)return true;const w=current();if(!w)return false;Object.assign(w,readFields(),{updatedAt:new Date().toISOString()});try{persist();$('#reuse-autosave').textContent='이 기기에 보관됨 · 다음에 쓰던 곳부터 이어져요.';return true;}catch(e){$('#reuse-autosave').textContent='저장하지 못했어요. 입력을 복사해 보관해 주세요. '+e.message;return false;}}
  function summary(){const records=selectedCreatorRecords(),w=current();$('#reuse-summary').innerHTML=`<p><strong>이어서 쓰는 재료</strong><br>기록 ${records.length}개 · 생각이 있는 기록 ${records.filter(r=>r.thought?.trim()).length}개 · 연결한 근거 ${w?.traces.length||0}개</p>`;}
  function renderResume(){
    const works=state.workspaces.filter(w=>w.viewpoint?.trim()||w.body?.trim()||w.selected?.length).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
    const markup=items=>items.map(w=>{const name=w.name||w.title||w.viewpoint?.split('\n')[0].slice(0,40)||'쓰던 글';return `<div class="reuse-saved-row"><button type="button" data-resume="${esc(w.id)}"><strong>${esc(name)}</strong><small>${w.body?'작성 중인 글':'시작한 생각'}</small></button><button type="button" class="reuse-delete" data-delete-work="${esc(w.id)}" aria-label="${esc(name)} 임시 저장 작업 삭제">삭제</button></div>`;}).join('');
    overview.hidden=!works.length;overview.innerHTML=`<h2>지난 작업을 이어 쓸까요?</h2><div class="reuse-saved-list">${markup(works.slice(0,1))}</div>`;
    studio.innerHTML=`<h2>쓰던 글</h2><div class="reuse-saved-list">${markup(works.slice(0,5))||'<p>글을 쓰기 시작하면 여기에서 이어 쓸 수 있어요.</p>'}</div>${works.length>5?`<details><summary>이전 작업 더 보기 (${works.length-5}개)</summary><div class="reuse-saved-list">${markup(works.slice(5))}</div></details>`:''}`;
    $$('[data-resume]').forEach(b=>b.onclick=()=>openCreator({workspaceId:b.dataset.resume}));
    $$('[data-delete-work]').forEach(b=>b.onclick=()=>{
      const id=b.dataset.deleteWork,w=state.workspaces.find(x=>x.id===id);if(!w)return;
      if(!window.confirm(`“${w.name||w.title||w.viewpoint?.split('\n')[0].slice(0,40)||'쓰던 글'}” 임시 저장 작업을 삭제할까요?\n이 작업의 자료 선택·관점·작성 중인 내용은 삭제됩니다. 원래 저장한 기록과 별도로 저장한 결과물은 유지됩니다.`))return;
      const before=state.workspaces;
      state.workspaces=before.filter(x=>x.id!==id);
      try{persist();}catch(e){state.workspaces=before;toast('삭제 내용을 저장하지 못했어요. 임시 저장 작업은 유지했어요.');return;}
      if(active===id){active=null;$('#creator-view').classList.remove('active');}
      renderResume();toast('임시 저장 작업을 삭제했어요. 원래 기록과 저장한 결과물은 그대로예요.');
    });
  }
  function decision(id){const w=current();return w.decisions[id]||(w.decisions[id]={excluded:false,role:'reference',note:''});}
  function chosenChanged(){const w=current();if(!w)return;selectedCreatorRecords().forEach(r=>decision(r.id).excluded=false);renderThoughts();renderDecisions();renderTrace();summary();saveWork();}
  function choose(id,excluded=false){const w=current();const selected=new Set(selectedCreatorRecords().map(r=>r.id));excluded?selected.delete(id):selected.add(id);decision(id).excluded=excluded;$('#creator-sources').innerHTML=creatorSourceOptions(selected);chosenChanged();findCandidates();}
  function findCandidates(all=showAll){showAll=all;const q=$('#reuse-query').value.trim()||$('#output-purpose').value.trim();const ranked=all?state.records.filter(r=>!DataTools.isExample(r)).sort((a,b)=>(b.capturedAt||b.savedAt||'').localeCompare(a.capturedAt||a.savedAt||'')).map(record=>({record,reason:'직접 고르기 · 최신 저장순'})):ReuseTools.rank(state.records,q,DataTools.isExample);const w=current();if(!w)return;const candidates=ranked.filter(x=>!w.decisions[x.record.id]?.excluded);$('#reuse-find-status').textContent=all?`내 기록 ${candidates.length}개. 관련성 순위가 아니라 저장순이에요.`:!q?'작업 목적이나 검색어를 적어주세요. 내 기록 전체 보기를 눌러 고를 수도 있어요.':`${candidates.length}개 자료에서 단어가 겹쳐요. 근거로 쓸지는 내용을 확인하고 선택하세요.`;
    $('#reuse-candidates').innerHTML=(all?candidates:candidates.slice(0,8)).map(({record:r,reason,excerpt})=>`<article class="reuse-record"><span class="reuse-tag">${selectedCreatorRecords().some(x=>x.id===r.id)?'선택됨':'자료 후보'}</span><strong>${esc(r.title)}</strong><small>${esc(reason)}</small><p>${esc((r.summary||'요약 없음').slice(0,220))}</p>${excerpt?`<small>검색어가 있는 본문 일부 · 자동 발췌</small><blockquote>${esc(excerpt)}</blockquote>`:''}${r.thought?`<blockquote>그때의 내 생각<br>${esc(r.thought)}</blockquote>`:''}<small>${r.sourceBody?'저장된 본문 있음 · 필요한 구절을 직접 확인하세요.':'본문 없음 · 주소·요약만으로 사실 근거를 확정하지 마세요.'}</small><div class="reuse-actions"><button type="button" data-pick="${esc(r.id)}">이번 작업에 사용</button><button type="button" data-skip="${esc(r.id)}">이번에는 제외</button><button type="button" data-inspect="${esc(r.id)}">본문·생각 확인</button></div></article>`).join('')+(!all&&candidates.length>8?'<p>관련 자료 8개를 먼저 보여드려요. 내 기록 전체 보기에서 나머지도 고를 수 있어요.</p>':'');
    $('#reuse-excluded').innerHTML=Object.entries(w.decisions).filter(([,d])=>d.excluded).map(([id,d])=>`<div class="reuse-record"><strong>${esc(state.records.find(r=>r.id===id)?.title||'원래 기록 없음')}</strong><label>제외 이유 (선택)<input data-note="${esc(id)}" value="${esc(d.note)}" maxlength="500"></label><button type="button" data-restore="${esc(id)}">제외 해제</button></div>`).join('')||'<p>제외한 자료가 없어요.</p>';
    $$('[data-pick]').forEach(b=>b.onclick=()=>choose(b.dataset.pick));$$('[data-skip]').forEach(b=>b.onclick=()=>choose(b.dataset.skip,true));$$('[data-restore]').forEach(b=>b.onclick=()=>{decision(b.dataset.restore).excluded=false;saveWork();findCandidates();});$$('[data-inspect]').forEach(b=>b.onclick=()=>inspectRecord(b.dataset.inspect));bindNotes();
  }
  function bindNotes(){$$('[data-note]').forEach(input=>input.oninput=()=>{decision(input.dataset.note).note=input.value;saveWork();});}
  function inspectRecord(id){window.memoiveOpenRecordFromCreator?.(id);}
  function renderThoughts(){const records=selectedCreatorRecords().filter(r=>r.thought?.trim());thoughts.innerHTML=`<h3>전에 남긴 생각, 다시 쓰지 마세요</h3>${records.length?records.map(r=>`<div class="reuse-record"><strong>${esc(r.title)}</strong><blockquote>${esc(r.thought)}</blockquote><button type="button" data-thought="${esc(r.id)}">이 생각을 이번 관점에 추가</button></div>`).join(''):'<p>선택한 자료에 내 생각이 아직 없어요. 아래에 이번 관점을 직접 남길 수 있어요.</p>'}<small>저장 이유와 생각은 기존 기록 문장을 그대로 보여줘요. 새 의견을 대신 만들지 않습니다.</small>`;$$('[data-thought]').forEach(b=>b.onclick=()=>{const r=state.records.find(r=>r.id===b.dataset.thought),input=$('#output-viewpoint');if(input.value.includes(r.thought))return toast('이미 이번 관점에 들어 있어요.');input.value=[input.value.trim(),r.thought].filter(Boolean).join('\n\n');current().reusedThoughts=[...new Set([...current().reusedThoughts,r.id])];saveWork();summary();toast('기존 생각을 그대로 추가했어요. 직접 다듬어도 돼요.');});}
  function renderDecisions(){const records=selectedCreatorRecords();rationale.innerHTML=`<h3>이 자료를 어디에 쓸까요?</h3>${records.map(r=>{const d=decision(r.id);return `<div class="reuse-record"><strong>${esc(r.title)}</strong><label>자료의 역할 (직접 선택)<select data-role="${esc(r.id)}">${Object.entries(ReuseTools.roles).map(([v,l])=>`<option value="${v}" ${d.role===v?'selected':''}>${l}</option>`).join('')}</select></label><label>쓸 부분·이유 (선택)<input data-note="${esc(r.id)}" value="${esc(d.note)}" maxlength="500" placeholder="예: 제안의 실행 순서를 참고"></label>${!r.sourceBody?`<button type="button" data-read="${esc(r.id)}">본문 불러오기·붙여 넣기</button>`:''}</div>`;}).join('')||'<p>자료를 고르면 활용 목적을 남길 수 있어요.</p>'}<small>반례·근거 여부는 자동 확정하지 않아요. 이 판단 메모는 기기에만 보관하며 AI에 자동 전송하지 않아요.</small>`;$$('[data-role]').forEach(s=>s.onchange=()=>{decision(s.dataset.role).role=s.value;saveWork();});$$('[data-read]').forEach(b=>b.onclick=()=>inspectRecord(b.dataset.read));bindNotes();}
  function renderTrace(){const w=current();if(!w)return;$('#reuse-trace-list').innerHTML=w.traces.map(t=>`<article class="reuse-record"><span class="reuse-tag">${{source:'원문에 관한 주장',interpretation:'해석·적용 제안',thought:'내 의견'}[t.kind]}</span><strong>${esc(t.claim)}</strong><blockquote>${esc(t.quote)}</blockquote><small>${esc(t.title)} · ${esc(ReuseTools.traceStatus(t,$('#output-body').value,state.records))}</small>${LinkReader.validateHttpUrl(t.url)?`<a href="${esc(t.url)}" target="_blank" rel="noopener">원문 열기</a>`:''}<button type="button" data-unlink="${esc(t.id)}">연결 해제</button></article>`).join('')||'<p>아직 문장에 연결한 근거가 없어요. AI 초안의 근거도 자동 검증됐다고 표시하지 않아요.</p>';$$('[data-unlink]').forEach(b=>b.onclick=()=>{w.traces=w.traces.filter(t=>t.id!==b.dataset.unlink);saveWork();renderTrace();summary();});const select=$('#reuse-trace-source'),prev=select.value;select.innerHTML='<option value="">기록 선택</option>'+selectedCreatorRecords().map(r=>`<option value="${esc(r.id)}">${esc(r.title)}</option>`).join('');if([...select.options].some(o=>o.value===prev))select.value=prev;renderTraceBody();}
  function renderTraceBody(){const r=state.records.find(r=>r.id===$('#reuse-trace-source').value);$('#reuse-trace-body').textContent=r?.sourceBody||'저장된 본문이 없어요. 위 자료에서 ‘본문 불러오기·붙여 넣기’를 사용하세요.';}
  const originalOpen=openCreator;
  openCreator=function(options={}){
    if($('#creator-view').classList.contains('active')&&!saveWork())return;
    let w=state.workspaces.find(w=>w.id===options.workspaceId)||state.workspaces.find(w=>options.outputId&&w.outputId===options.outputId);
    restoring=true;if(!w)$('#reuse-name').value='';originalOpen({recordIds:w?.selected||options.recordIds||[],outputId:options.outputId||w?.outputId||null});
    if(!w){w=ReuseTools.cleanWorkspaces([{id:crypto.randomUUID(),...readFields(),outputId:options.outputId||'',selected:options.recordIds||selectedCreatorRecords().map(r=>r.id),traces:state.outputs.find(o=>o.id===options.outputId)?.traces||[]}])[0];state.workspaces.push(w);}
    active=w.id;$('#reuse-name').value=w.name;$('#output-purpose').value=w.purpose;$('#output-viewpoint').value=w.viewpoint;$('#output-type').value=w.type;$('#output-tone').value=w.tone;$('#output-title').value=w.title;$('#output-body').value=w.body;$('#output-used').checked=w.used;$('#output-use-note').value=w.useNote;$('#output-use-fields').hidden=!w.used;analysisDraftOrigin=w.draftOrigin;$('#creator-sources').innerHTML=creatorSourceOptions(new Set(w.selected));$('#creator-draft').classList.toggle('hidden',!w.body);setShareFormat(w.shareFormat);$('#creator-title').textContent=w.name||'지난 기록으로 이번 작업을';$('#creator-step').textContent='자료 선택 · 기존 생각 재사용 · 근거를 보며 작성';$('#creator-include-source').checked=false;$('#reuse-query').value='';$('#reuse-claim').value='';$('#reuse-quote').value='';$('#reuse-trace-status').textContent='';$('#reuse-previous').innerHTML='<option value="">이전 작업 선택</option>'+state.workspaces.filter(x=>x.id!==active&&(x.purpose||x.viewpoint)).map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.title||x.purpose||'이전 작업')}</option>`).join('');const missing=w.selected.filter(id=>!state.records.some(r=>r.id===id));restoring=false;chosenChanged();findCandidates();renderOutputSources(selectedCreatorRecords().map(r=>r.id));if(missing.length)$('#reuse-autosave').textContent=`이전 자료 ${missing.length}개를 찾지 못했어요. 삭제 여부를 확인해 주세요. 작성한 글은 유지했어요.`;
  };
  const originalApply=applyOutputDraft;
  applyOutputDraft=function(...args){originalApply(...args);saveWork();renderTrace();summary();};
  const originalRequest=requestAiDraft;
  requestAiDraft=async function(payload){
    const reject=message=>{toast(message);const e=new Error(message);e.code='AI_CANCELLED';throw e;};
    if(payload.records?.length>8)reject('AI에는 한 번에 자료 8개까지 보낼 수 있어요. 이번에 쓸 자료만 골라주세요.');
    if(payload.purpose?.length>600||payload.viewpoint?.length>1200||payload.records?.some(r=>r.thought?.length>1000))reject('내용이 잘리지 않도록 목적 600자·관점 1,200자·기록별 생각 1,000자 이내로 골라주세요. 원래 작업은 보존했어요.');
    const fingerprint=()=>{const fields=readFields();delete fields.draftOrigin;return JSON.stringify({fields,sources:selectedCreatorRecords().map(r=>[r.id,r.sourceBody,r.summary,r.thought])});};
    const workspace=active,before=fingerprint(),previousOrigin=analysisDraftOrigin,eventIds=new Set(state.analytics.events.map(e=>e.id));const result=await originalRequest(payload);
    if(workspace!==active||before!==fingerprint()){
      if(workspace===active)analysisDraftOrigin=previousOrigin;
      const event=[...state.analytics.events].reverse().find(e=>!eventIds.has(e.id)&&e.name==='ai_measure_v1'&&JSON.parse(e.value||'{}').kind==='draft');
      if(event){event.value=JSON.stringify({kind:'draft',status:'discarded',reason:'context_changed'});try{persist();}catch{}}
      reject('요청 중 작업이나 자료가 바뀌어 이전 응답을 적용하지 않았어요.');
    }return result;
  };
  // A response must never replace edits made while the request is running.
  const originalRefine=refineOutputWithAi;
  const packButton=document.createElement('button');packButton.type='button';packButton.textContent='목적·자료·내 생각을 한 번에 복사';host.append(packButton);
  packButton.onclick=async()=>{const w=current();if(!w)return;const records=selectedCreatorRecords();const text=['# '+(w.name||'이번 작업'),'작업 목적: '+$('#output-purpose').value,'내 관점 (직접 작성·재사용): '+$('#output-viewpoint').value,...records.map(r=>['## '+r.title,'출처: '+(r.url||r.source||'직접 기록'),'자료 요약 (원문과 확인 필요): '+r.summary,'저장한 내 생각: '+(r.thought||'미작성'),'이번에 쓸 역할: '+ReuseTools.roles[decision(r.id).role],'활용 메모 (직접 작성): '+decision(r.id).note].join('\n')),...w.traces.map(t=>'결과물 문장: '+t.claim+'\n원문 발췌: '+t.quote+'\n연결 상태: '+ReuseTools.traceStatus(t,$('#output-body').value,state.records))].join('\n\n');try{await navigator.clipboard.writeText(text);toast('이번 작업의 맥락과 자료를 함께 복사했어요.');}catch{toast('복사 권한을 확인해 주세요. 저장된 작업은 그대로예요.');}};
  $('#ai-refine-output').onclick=async()=>{await originalRefine();saveWork();renderTrace();};
  const originalSave=saveOutput;
  saveOutput=function(){if(!saveWork())return;const w=current();originalSave();if(!$('#creator-view').classList.contains('active')){const output=state.outputs.find(o=>o.id===state.currentOutputId)||state.outputs[0];if(output){w.outputId=output.id;output.traces=w.traces;output.workspaceId=w.id;try{persist();}catch(e){toast('결과물은 저장됐지만 작업 연결 저장은 실패했어요.');}}renderResume();}};$('#save-output').onclick=()=>saveOutput();
  $('#close-creator').onclick=()=>{if(saveWork()){$('#creator-view').classList.remove('active');renderResume();}};
  window.memoiveCloseWork=()=>{if(saveWork()){$('#creator-view').classList.remove('active');renderResume();return true;}return false;};
  $('#creator-view').addEventListener('input',e=>{if(['reuse-query','reuse-claim','reuse-quote'].includes(e.target.id))return;saveWork();if(e.target.id==='output-body'){renderTrace();}summary();});
  $('#creator-view').addEventListener('change',e=>{if(e.target.closest('#creator-sources'))chosenChanged();else if(['output-type','output-tone','output-used','output-use-note'].includes(e.target.id))saveWork();});
  $('#reuse-find').onclick=()=>findCandidates(false);$('#reuse-browse').onclick=()=>findCandidates(true);$('#reuse-query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();findCandidates(false);}};
  // Source acquisition stays in the current task; blocked sites still need user-provided text.
  const bodyPanel=document.createElement('details');bodyPanel.className='reuse-panel';bodyPanel.innerHTML='<summary>본문을 직접 붙여 넣어 이어가기</summary><p>자동 읽기가 막힌 자료는 원문을 복사해 여기에 넣으세요. 로그인·유료 접근 제한을 우회하지 않아요.</p><label>본문을 채울 자료<select id="reuse-body-record"></select></label><label>직접 확인한 본문<textarea id="reuse-body-input" rows="5"></textarea></label><button type="button" id="reuse-body-save">본문 저장하고 작업 계속</button><p id="reuse-body-status" role="status"></p>';rationale.after(bodyPanel);
  const baseDecisions=renderDecisions;renderDecisions=function(){baseDecisions();$('#reuse-body-record').innerHTML='<option value="">자료 선택</option>'+selectedCreatorRecords().filter(r=>!r.sourceBody).map(r=>'<option value="'+esc(r.id)+'">'+esc(r.title)+'</option>').join('');bodyPanel.hidden=!selectedCreatorRecords().some(r=>!r.sourceBody);};
  $('#reuse-body-save').onclick=()=>{const r=selectedCreatorRecords().find(r=>r.id===$('#reuse-body-record').value),content=$('#reuse-body-input').value.trim();if(!r||r.sourceBody)return $('#reuse-body-status').textContent='본문이 없는 선택 자료를 골라주세요.';if(content.length<80||content.length>200000)return $('#reuse-body-status').textContent='본문은 80자 이상, 200,000자 이하로 붙여 넣어 주세요.';try{applyArticle(r,{title:r.title,published:r.sourceDate,content,method:'manual'});persist();$('#reuse-body-input').value='';renderDecisions();renderTrace();findCandidates();toast('본문을 저장했어요. 선택한 자료와 작업은 그대로예요.');}catch(e){$('#reuse-body-status').textContent=e.message;}};
  $('#reuse-copy-context').onclick=async()=>{const prev=state.workspaces.find(w=>w.id===$('#reuse-previous').value);if(!prev)return;if(($('#output-purpose').value||$('#output-viewpoint').value)&&!await window.memoiveConfirm('이번 작업의 목적과 관점을 선택한 이전 작업 내용으로 바꿀까요?'))return;$('#output-purpose').value=prev.purpose;$('#output-viewpoint').value=prev.viewpoint;saveWork();findCandidates();summary();};
  $('#reuse-selected-sentence').onclick=()=>{const input=$('#output-body');$('#reuse-claim').value=input.value.slice(input.selectionStart,input.selectionEnd);if(!$('#reuse-claim').value)$('#reuse-trace-status').textContent='위 결과물 편집기에서 문장을 먼저 선택해 주세요.';};
  let selectedQuote='';document.addEventListener('selectionchange',()=>{const selection=window.getSelection();if(selection?.rangeCount&&$('#reuse-trace-body').contains(selection.anchorNode))selectedQuote=selection.toString();});
  $('#reuse-selected-quote').onclick=()=>{$('#reuse-quote').value=selectedQuote;};$('#reuse-trace-source').onchange=()=>{selectedQuote='';$('#reuse-quote').value='';renderTraceBody();};
  $('#reuse-add-trace').onclick=()=>{try{const r=selectedCreatorRecords().find(r=>r.id===$('#reuse-trace-source').value),t=ReuseTools.makeTrace(r,$('#reuse-claim').value,$('#reuse-quote').value,$('#output-body').value,$('#reuse-kind').value);current().traces.push(t);if(saveWork()){$('#reuse-trace-status').textContent='문장과 발췌를 연결했어요. 이 근거가 주장을 뒷받침하는지는 직접 확인하세요.';renderTrace();summary();}}catch(e){$('#reuse-trace-status').textContent=e.message;}};
  // The legacy record entry prefilled thought after opening; preserve it in the workbench too.
  const originalContinue=continueFromRecord;$('#create-from-record').onclick=()=>{originalContinue();saveWork();};
  const originalStudio=renderStudio;renderStudio=function(){originalStudio();renderResume();};
  const originalHome=renderHome;renderHome=function(){originalHome();renderResume();};
  window.addEventListener('pagehide',()=>{if($('#creator-view').classList.contains('active'))saveWork();});
  renderResume();
})();
