const DAANGN_URL = "https://careers.daangn.com/blog/post/%EB%8B%B9%EA%B7%BC-%EC%9D%B8%ED%84%B4-%ED%9A%8C%EC%9D%98%EB%B4%87-%EB%8B%B9%EB%B2%88%EC%9D%B4-%EB%B9%84%EA%B0%9C%EB%B0%9C%EC%9E%90-ai/";

const seedRecords = [
  {
    id:"daangn-dangbeoni", type:"article", typeLabel:"ARTICLE", date:"2026.04.30",
    title:"비개발자로 회의봇 만들기는 처음이라",
    source:"당근 팀 채용 · Mike (피플팀 GA 인턴)", url:DAANGN_URL,
    summary:"개발 경험이 없는 피플팀 인턴이 Claude와 대화하듯 2주 만에 사내 회의봇 ‘당번이’를 만들고, 운영 오류와 낮은 사용률을 해결하며 전사 도구로 성장시킨 기록이에요.",
    points:[
      "회의 지연, 비어 있는 예약 회의실, 위치 탐색이라는 작은 불편에서 출발해 회의 정보·참석 응답·오피스 맵·예약 해제를 하나의 Slack 메시지에 담았어요.",
      "개인 캘린더가 다른 사용자에게 노출되는 사고를 겪은 뒤 계정별 권한과 토큰을 분리하고 테스트 계정으로 검증하는 안전장치를 마련했어요.",
      "공지보다 실제 회의에서 자연스럽게 사용 경험을 보여주고 알림 수신 여부를 직접 선택하게 한 방식이 확산에 효과적이었어요. 글에 따르면 251명이 연결했고 하루 평균 약 400건의 알림을 보냈어요."
    ],
    quote:"기능을 만드는 것과 사람들이 실제로 쓰게 만드는 것은 완전히 다른 일이었다.",
    question:"MEMOIVE가 사용자에게 설명되지 않아도 자연스럽게 가치를 경험하게 하려면 어떤 순간에 등장해야 할까요?",
    thought:"알림 기능보다 ‘기존 행동 안에서 자연스럽게 경험하게 하는 방법’을 먼저 설계해야겠다.",
    topics:["비개발자 AI","업무 자동화","제품 도입"]
  },
  {id:"design-memory",type:"video",typeLabel:"VIDEO",date:"2026.09.11",title:"기억에 남는 순간을 설계하는 제품",source:"YouTube · Design Better",summary:"기능 수보다 사용자가 감정을 느끼는 결정적 순간이 제품의 기억을 만든다는 이야기예요.",points:["첫 성공 경험을 빠르게 제공해요.","작은 문구와 반응이 다음 행동을 만들어요.","사용자가 떠올릴 한 장면을 먼저 설계해요."],quote:"사람은 기능보다 순간을 기억한다.",question:"MEMOIVE에서 사용자가 가장 먼저 기억했으면 하는 순간은 무엇일까요?",thought:"요약이 완성되는 순간보다 내 생각 한 줄이 기록에 붙는 순간을 강조하자.",topics:["제품 경험","기록 습관"]},
  {id:"image-timeline",type:"image",typeLabel:"IMAGE",date:"2026.09.08",title:"시간에 따라 생각이 이어지는 화면",source:"스크린샷 · 개인 보관함",summary:"과거의 메모와 지금의 생각을 같은 흐름에서 비교해 보는 세로형 기록 화면이에요.",points:["날짜보다 생각의 변화가 먼저 보여요.","색을 줄여 내용에 집중해요.","관련 기록을 선으로 연결해요."],quote:"기록은 쌓이는 것이 아니라 이어지는 것이다.",question:"이 화면에서 꼭 남겨야 할 나만의 맥락은 무엇일까요?",thought:"같은 주제를 3개월 뒤 다시 물어보는 기능이 있으면 좋겠다.",topics:["화면 영감","재발견"]},
  {id:"voice-capture",type:"voice",typeLabel:"VOICE",date:"2026.09.05",title:"저장한 이유를 먼저 묻는 아이디어",source:"음성 메모 · 00:38",summary:"콘텐츠 요약보다 사용자가 저장한 이유를 빠르게 남기게 하면 기록의 개인적 가치가 커진다는 아이디어예요.",points:["질문은 한 번에 하나만 보여줘요.","음성으로도 답할 수 있게 해요.","답하지 않아도 원본 저장은 끝나요."],quote:"한 줄의 이유가 요약을 나의 기록으로 바꾼다.",question:"저장 직후 가장 부담 없이 답할 수 있는 질문은 무엇일까요?",thought:"‘왜 저장했나요?’보다 구체적인 맥락형 질문이 좋겠다.",topics:["기록 습관","음성"]}
];

const state={screen:"today",filter:"all",query:"",captureType:"link",currentId:null,records:JSON.parse(localStorage.getItem("memoive-records-v2-ready")||"null")||seedRecords};
const $=(s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const escapeHtml=(v="")=>v.replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function persist(){localStorage.setItem("memoive-records-v2-ready",JSON.stringify(state.records))}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2300)}
function go(screen){state.screen=screen;$$('.screen').forEach(el=>el.classList.toggle('active',el.dataset.screen===screen));$$('.bottom-nav [data-go]').forEach(el=>el.classList.toggle('active',el.dataset.go===screen));if(screen==='library')renderRecords();window.scrollTo(0,0)}
function openSheet(id){$('#overlay').classList.add('active');$(id).classList.add('active')}
function closeSheets(){$('#overlay').classList.remove('active');$$('.sheet').forEach(el=>el.classList.remove('active'))}
function renderRecords(){const q=state.query.trim().toLowerCase();const found=state.records.filter(r=>(state.filter==='all'||r.type===state.filter)&&[r.title,r.source,r.summary,r.thought,...r.topics].join(' ').toLowerCase().includes(q));$('#record-list').innerHTML=found.map((r,i)=>`<button class="record-item" data-record-id="${r.id}"><span class="record-index">${String(i+1).padStart(2,'0')}</span><span><strong>${escapeHtml(r.title)}</strong><small>${escapeHtml(r.source)} · ${r.thought?'내 기록 있음':'이어 쓰기'}</small></span><b>→</b></button>`).join('');$('#empty-state').classList.toggle('hidden',found.length>0);$$('.record-item').forEach(el=>el.onclick=()=>openRecord(el.dataset.recordId))}
function openRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.currentId=id;$('#detail-type').textContent=r.typeLabel;$('#detail-title').textContent=r.title;$('#detail-source').textContent=`${r.source} · ${r.date}`;$('#detail-topics').innerHTML=r.topics.map(t=>`<span># ${escapeHtml(t)}</span>`).join('');$('#detail-summary').textContent=r.summary;$('#detail-points').innerHTML=r.points.map(p=>`<li>${escapeHtml(p)}</li>`).join('');$('#detail-quote').textContent=r.quote;$('#detail-question').textContent=r.question;$('#detail-thought').textContent=r.thought||'아직 나만의 기록이 없어요. 한 문장이면 충분해요.';$('#detail-thought').classList.toggle('empty',!r.thought);const source=$('#source-link');source.href=r.url||'#';source.style.display=r.url?'flex':'none';$('#detail-view').classList.add('active');$('#detail-view').scrollTop=0}
function openThought(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.currentId=id;$('#thought-question').textContent=r.question;$('#thought-input').value=r.thought||'';openSheet('#thought-sheet');setTimeout(()=>$('#thought-input').focus(),300)}
function saveThought(){const value=$('#thought-input').value.trim();if(!value)return toast('한 문장만 남겨주세요.');const r=state.records.find(x=>x.id===state.currentId);r.thought=value;persist();closeSheets();openRecord(r.id);toast('나만의 기록을 저장했어요.')}
function selectType(type){state.captureType=type;$$('.capture-tabs button').forEach(el=>el.classList.toggle('active',el.dataset.type===type));$$('.capture-panel').forEach(el=>el.classList.toggle('active',el.dataset.panel===type))}
function demoRecord(type,value,note){const isDaangn=/careers\.daangn\.com/i.test(value);if(type==='link'&&isDaangn){const copy=structuredClone(seedRecords[0]);copy.id=`daangn-${Date.now()}`;copy.thought=note||copy.thought;return copy}const meta={id:`record-${Date.now()}`,date:new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'}).replace(/\. /g,'.').replace('.',''),thought:note,question:'이 내용을 지금의 나에게 남겨야 하는 이유는 무엇일까요?',topics:['새로운 기록']};if(type==='image')return {...meta,type,typeLabel:'IMAGE',title:'새로 저장한 이미지 레퍼런스',source:'이미지',summary:'이미지의 문자와 시각 요소를 함께 살펴 다시 찾기 쉬운 기록으로 정리했어요.',points:['이미지 속 문자를 추출했어요.','주요 구성과 색을 설명했어요.','연결할 주제를 제안했어요.'],quote:'보이는 장면에도 남겨야 할 맥락이 있다.'};if(type==='voice')return {...meta,type,typeLabel:'VOICE',title:'새로 남긴 음성 아이디어',source:'음성 메모',summary:'말로 남긴 아이디어를 글로 옮기고 중심 생각과 다음 행동을 구분했어요.',points:['원본 음성을 보존해요.','중심 생각을 한 문장으로 만들어요.','실행할 내용을 구분해요.'],quote:'떠오른 순간을 놓치지 않는 것이 기록의 시작이다.'};if(type==='text')return {...meta,type,typeLabel:'TEXT',title:value.slice(0,35)||'새 텍스트 기록',source:'직접 작성',summary:value||'사용자가 남긴 글의 핵심 생각을 정리했어요.',points:['원문을 그대로 보존해요.','핵심 문장을 찾아요.','관련 주제를 연결해요.'],quote:value.slice(0,60)||'내가 직접 남긴 기록.'};let host='새 웹 콘텐츠';try{host=new URL(value).hostname.replace('www.','')}catch{}return {...meta,type:'article',typeLabel:'ARTICLE',title:'새로 저장한 웹 콘텐츠',source:host,url:value,summary:'공유한 링크의 중심 내용을 다시 이해하기 쉽게 한 문장으로 정리한 시연용 기록이에요.',points:['원문과 출처를 먼저 보존해요.','반복되는 핵심 내용을 찾아요.','관련 관심사를 연결해요.'],quote:'좋은 수집은 다음 생각으로 이어진다.'}}
async function analyze(record){closeSheets();const view=$('#analysis-view');const steps=[$('#step-read'),$('#step-summary'),$('#step-connect')];steps.forEach(s=>s.className='');view.classList.add('active');for(const step of steps){step.classList.add('active');await new Promise(r=>setTimeout(r,480));step.classList.remove('active');step.classList.add('done')}state.records.unshift(record);persist();view.classList.remove('active');openRecord(record.id);toast('새 기록이 내 아카이브에 살아났어요.')}
function submitCapture(event){event.preventDefault();let value='';if(state.captureType==='link')value=$('#capture-link').value.trim();if(state.captureType==='text')value=$('#capture-text').value.trim();if(state.captureType==='image')value=$('#capture-image').files[0]?.name||'';if(state.captureType==='link'&&!value)return toast('콘텐츠 주소를 넣어주세요.');if(state.captureType==='text'&&!value)return toast('남길 글을 적어주세요.');analyze(demoRecord(state.captureType,value,$('#capture-note').value.trim()))}
function setDate(){const d=new Date();$('#date-day').textContent=String(d.getDate()).padStart(2,'0');$('#date-month').textContent=d.toLocaleDateString('en-US',{month:'short'}).toUpperCase()}
$$('[data-go]').forEach(el=>el.onclick=()=>go(el.dataset.go));$('#hero-capture').onclick=$('#nav-capture').onclick=()=>openSheet('#capture-sheet');$('#open-search').onclick=()=>{go('library');setTimeout(()=>$('#record-search').focus(),200)};$('.feature-clipping').onclick=()=>openRecord('daangn-dangbeoni');$('.memory-prompt').onclick=()=>openThought('daangn-dangbeoni');$('#close-detail').onclick=()=>$('#detail-view').classList.remove('active');$('#edit-thought').onclick=()=>openThought(state.currentId);$('#save-thought').onclick=saveThought;$('#overlay').onclick=closeSheets;$$('.close-sheet').forEach(el=>el.onclick=closeSheets);$$('.capture-tabs button').forEach(el=>el.onclick=()=>selectType(el.dataset.type));$('#capture-form').onsubmit=submitCapture;$('#voice-button').onclick=()=>{const on=$('#voice-button').classList.toggle('recording');$('#voice-button strong').textContent=on?'듣고 있어요… 다시 누르면 완료':'눌러서 음성 기록 시작'};$('#record-search').oninput=e=>{state.query=e.target.value;renderRecords()};$$('.filters button').forEach(el=>el.onclick=()=>{state.filter=el.dataset.filter;$$('.filters button').forEach(b=>b.classList.toggle('active',b===el));renderRecords()});$('#share-record').onclick=async()=>{const r=state.records.find(x=>x.id===state.currentId);try{if(navigator.share)await navigator.share({title:r.title,text:r.summary,url:r.url});else await navigator.clipboard.writeText(r.url||r.summary);toast('기록 내용을 복사했어요.')}catch{}};setDate();renderRecords();
