/* Auto mode is an explicit device preference. Personal context remains manual. */
(()=>{
  const key='memoive-auto-summary-v1';
  let enabled=false;try{enabled=localStorage.getItem(key)==='true';}catch{}
  const main=$('#detail-view main'),rating=$('.summary-rating'),summary=$('.one-line');
  main.prepend(summary,$('#source-evidence-details'));
  $('.my-thought').after($('#record-progress'));
  main.append($('#saved-source'),rating);
  const privacy=document.createElement('details');privacy.className='ai-privacy';
  const label=document.createElement('summary');label.textContent='AI 전송·개인정보 안내';privacy.append(label);$('#insight-status').before(privacy);privacy.append($('#insight-status'));
  const caution=$('#detail-view .notice');if(caution)privacy.append(caution);
  $('.insight-options > summary').textContent='AI 설정 · 내 맥락을 더해 다시 정리';
  const option=document.createElement('label');option.className='context-check';
  option.innerHTML='<input type="checkbox" id="auto-summary-enabled">본문 자동 정리';privacy.before(option);
  const help=document.createElement('small');help.textContent='켜면 열거나 저장한 기록의 제목·본문·관점을 Gemini로 보내요. 내 생각·고민은 자동으로 보내지 않아요.';option.after(help);
  const status=document.createElement('p');status.id='auto-summary-status';status.setAttribute('role','status');summary.append(status);
  const attempts=new Set(),bodyAttempts=new Set(),queue=new Map();let running=false,controller;
  const input=$('#auto-summary-enabled');input.checked=enabled;
  input.onchange=()=>{try{localStorage.setItem(key,String(input.checked));enabled=input.checked;if(!enabled){queue.clear();controller?.abort();}const r=state.records.find(x=>x.id===state.currentId);if(r)renderInsight(r);}catch{input.checked=enabled;toast('자동 정리 설정을 저장하지 못했어요.');}};
  const originalRender=renderInsight;
  renderInsight=function(record){originalRender(record);$('.my-thought .eyebrow').textContent='내 생각';$('#edit-thought').textContent='내 생각 다듬기';$('#source-evidence-details').open=!!InsightTools.current(record,state.role);if(!enabled){status.textContent='자동 정리가 꺼져 있어요. AI 설정에서 한 번 켜면 이후에는 본문을 바로 정리해요.';return;}const prompt=$('#key-points-prompt');if(prompt)prompt.hidden=true;$('#source-evidence-details').hidden=!InsightTools.current(record,state.role);if(InsightTools.current(record,state.role)?.analysisVersion===3){status.textContent='저장된 AI 정리';return;}if(!record.sourceBody){status.textContent=record.fetchStatus==='failed'?(record.fetchError||'본문을 자동으로 읽지 못했어요. 원문 링크를 확인해 주세요.'):'본문을 불러온 뒤 자동으로 정리해요.';if(record.url&&!bodyAttempts.has(record.id)&&!linkJobs.has(record.id)){bodyAttempts.add(record.id);queueMicrotask(()=>{if(enabled&&state.currentId===record.id&&!record.sourceBody&&!linkJobs.has(record.id))retrySource();});}return;}if(record.sourceBody.trim().length<80||record.sourceBody.length>60000){status.textContent='자동 정리는 본문 80~60,000자를 지원해요. AI 설정에서 전송 범위를 확인해 주세요.';return;}const stamp=InsightTools.stamp(record),id=record.id+'|'+state.role+'|'+stamp;if(!attempts.has(id)&&!insightJobs.has(record.id)&&INSIGHT_ENDPOINT){attempts.add(id);queue.set(id,{id:record.id,role:state.role,stamp,body:record.sourceBody,title:record.title});status.textContent='AI가 정리하고 있어요. 기다리는 동안 기록을 읽거나 생각을 남길 수 있어요.';void drain();}};
  async function drain(){if(running||!enabled)return;running=true;try{while(queue.size&&enabled){const [signature,job]=queue.entries().next().value;queue.delete(signature);const record=state.records.find(r=>r.id===job.id);if(!record||InsightTools.current(record,job.role)?.analysisVersion===3||InsightTools.stamp(record)!==job.stamp)continue;insightJobs.add(job.id);controller=new AbortController();const timer=setTimeout(()=>controller.abort(),55000);try{const response=await fetch(INSIGHT_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({title:job.title.slice(0,200),body:job.body,role:job.role,context:{},protocolVersion:2})});const data=await response.json();if(!response.ok)throw Error(data.message||'AI 연결을 확인해 주세요.');if(!enabled)continue;const result=MemoiveContract.validate(data,job.body),current=state.records.find(r=>r.id===job.id);if(!current||InsightTools.stamp(current)!==job.stamp)continue;if(result.analysisVersion!==3)throw Error('새 분석 형식의 연결을 확인 중이에요. 잠시 후 다시 시도해 주세요.');current.aiInsights={...current.aiInsights,[job.role]:{...result,sourceStamp:job.stamp,createdAt:new Date().toISOString(),inputContext:{},sourceChars:job.body.length}};persist();if(state.currentId===job.id&&state.role===job.role)renderInsight(current);}catch(error){if(state.currentId===job.id)status.textContent=enabled?(error.name==='AbortError'?'정리가 지연되어 중단했어요. 원문은 그대로이며 AI 설정에서 다시 시도할 수 있어요.':error.message):'';}finally{clearTimeout(timer);insightJobs.delete(job.id);if(state.currentId===job.id){const current=state.records.find(r=>r.id===job.id),message=status.textContent;if(current){renderInsight(current);if(!InsightTools.current(current,state.role))status.textContent=message;}}}}}finally{running=false;}}
  // Only this deliberate settings route exposes the device opt-in shortcut.
  if(location.hash==='#auto-summary'){
    const panel=document.createElement('section');panel.className='reuse-panel';panel.innerHTML='<h2>본문 자동 정리</h2><p>기록을 열거나 저장하면 제목·본문·관점을 Gemini로 전송해 정리합니다. 내 생각·고민은 제외합니다. 무료 등급의 전송 내용은 Google 제품 개선에 사용될 수 있습니다.</p><button type="button" id="enable-auto-summary">이 브라우저에서 자동 정리 켜기</button><p role="status" id="auto-setup-status"></p>';$('.screen[data-screen="home"] .page').prepend(panel);$('#enable-auto-summary').onclick=()=>{input.checked=true;input.onchange();if(enabled){$('#auto-setup-status').textContent='자동 정리를 켰어요. 이제 기록을 열면 추가 입력 없이 정리됩니다.';$('#enable-auto-summary').disabled=true;history.replaceState({},'',location.pathname+location.search);}};
  }
})();
